# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d73826be00d8a4dcc5ea49eafaea4e199144c583e6664db87f7d4b4500f1837ddf59c8d0cc623e177b0b48fc9493580f85c37e5452d868a23f2c0cf065c0aebc

test:
  secret_key_base: 31ea5bd57c186fb34812b2a1cd93b7a0ff65bc1942f9fd4ea1351b2da95e5a0414f95ae7cc41cf97a47fe59cc04c44d5a92eedc8e652f0bf598123a07a62535a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
